version: "3.5"
services:
  jenkins:
    container_name: jenkins
    image: mhnj7/jenkins-mh:latest
    networks:
      - devopslab
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /home/mhnj7/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
  postgres:
    container_name: postgres
    image: postgres:latest
    networks:
      - devopslab
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonarpasswd
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
  sonarqube:
    container_name: sonarqube
    image: sonarqube:latest
    ports:
      - "9000:9000"
      - "9092:9092"
    networks:
      - devopslab
    environment:
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_JDBC_PASSWORD: sonarpasswd
      SONARQUBE_JDBC_URL: "jdbc:postgresql://postgres:5432/sonar"
    depends_on:
      - postgres

networks:
  devopslab:
    name: devopslab
